### ISSUE TITLE
关于一级标题分页后的“段前”间距问题

### ISSUE THREAD

**Issue by ilcpm** [qbh16/ThuWordThesis#1]
> Word中的一个bug是，如果页面顶部的文字不从新节开始，那么文字的段前距会被省略。即使在“文件–选项–高级–以下对象的布局选项”中，取消勾选“取消页面顶部的多余行距”仍无法生效。让页面顶部的标题从新一页的新节开始，才能保证段前距可以正常显示。

这个问题个人经验可能是由于Office在新的软件版本中去掉了相关的支持。一种处理方式是，让文档保持Office 2010的兼容性支持，其后在段落设置中设置“段前分页”即可，如图

![image](https://user-images.githubusercontent.com/36830343/119389677-88eed280-bcfe-11eb-83b0-d0dfa8dd9d4a.png)

该文件来自于pandoc(pandoc为文档转换工具，重点工作对象为Markdown到各种格式的互相转换，见 https://pandoc.org )的默认Word，具体兼容性方法见下图

![image](https://user-images.githubusercontent.com/36830343/119389828-b9cf0780-bcfe-11eb-8a19-1091ba42c52f.png)

这种方式目前发现除了无法插入3D图像以外，并无大的影响，SVG图片是Office较新版本中引入的功能，可以插入，公式使用#加数字设置编号的功能也可以正常使用（具体这两个功能在Office2010中如何显示尚未验证）

[1.docx](https://github.com/qbh16/ThuWordThesis/files/6534178/1.docx)

**Comment by ilcpm** [comment]
另，模版中关于Word的各种细节反映出的作者Word功底深表佩服，是否可以提供一些“参考文献”以供阅读？

文档中提到的各项细节的列出和验证也存在巨大的管理难度，是否有相关的管理方案可供参考？

不胜感激

**Comment by fatalerror-i** [comment]
您好，这里将逐点讨论上述问题。

1. 首先很遗憾，不知为何我的Word 2019的首选项中，对`.docx`文件并没有“兼容性选项”的存在，而只对`.doc`文件有“兼容性选项”，因此暂时无法对你的操作进行交叉验证。
2. 其次，个人不建议通过保持向较前版本Word的兼容性支持来解决这样一个较小的问题，因为这可能导致其他的未知问题。我曾经遇到过这样的问题：在`.docx`文件的双栏文字中加入脚注，脚注会同样被分隔为两栏，但在另存为`.doc`格式以后脚注变为单栏。不同版本的Word如何处理相同的对象还有待考察。
3. 在你的测试文档中。第二页顶端标题的段前距可以显示，但尽管和第一页标题的段前距数值设置一样，二者实际页面高度并不一样……
4. pandoc对中文的支持一直并不是很好，再加上其不能处理格式较为复杂的文档，因此暂不作考虑。
5. 各种问题的解决无非是逢山开路、遇水架桥，不过还是需要一定Word基础。我最初系统学习Word是靠看各路Office培训视频入门的，也在知乎上看过许多问题。我还下载过几本Word教程书籍，但是因为有的版本久远所以并未细看，现在看来了解从前版本的Word还是很有意义的：《Word排版艺术》《Word非常接触》《就这样享用Word》。
6. 我并没能读懂你这段话里的“管理”具体指什么……如果是样式的话，通过样式管理器可以直接迁移；如果是页面、页码等版面格式的话，则暂时没有很好的迁移方法，详见3.6节。
> 文档中提到的各项细节的列出和验证也存在巨大的管理难度，是否有相关的管理方案可供参考？

祝好！

**Comment by ilcpm** [comment]
1. 经过测试，Word在新版确实是不会主动显示相关设置，需要文件本身就是从旧版本创建，或者说拆开Word文档之后，里面具有相关的兼容性xml标签才可以。手动创建的话，可以先创建具有兼容性选项的doc文件而后另存为docx文件，此时在另存为的窗口中就会出现与旧版本Word兼容的兼容性复选框，从而产生具有兼容性选项的docx文件
2. 这种方式确实是不太好，只是说可以作为一种比较无奈的选择
3. 关于这一点我确实是没有注意到，不过在我们的文档中确实是一样高的，很奇怪（见下文）
4. 我们现在在做一个用pandoc把Markdown转换为Word的python插件，不过由于项目很复杂，目前功能差不多完成了，但是文档乱成一团，还需要一些时间优化文档，项目地址 https://github.com/ilcpm/pandoc_markdown2docx_instuction （仓库内的文件需要更新，我们目前是在私有仓库中开发的）。附件中是我们最新的转换结果，整个文档从Markdown出来之后就修改了一下兼容性设置等，然后手动处理了一下目录中的字号（学校要求太奇葩了）
   - 在这个文档中，我测试确实是分节符之后的一级标题和不是分节符之后的一级标题的位置是一样高的，以文档阿拉伯页码第1 2页为例![image](https://user-images.githubusercontent.com/36830343/119495689-3c0a0b00-bd95-11eb-8ca5-3a904968f949.png)
5. 原来如此，我自己的Word经验全都是自己遇到问题摸索出来的，也尝试找过一些书籍和视频来看，但是发现所讲内容几乎都是我知道的，而且讲课逻辑也不太认可，所以其实大部分都没怎么看。
   - 关于Word，我个人的观点是，生活学习中需要学的东西太多了，Word只是那么多工具中的一个，而我自己的水平现在也够用了（在看到您写的东西之前还一度有些自大），比起花时间再去研究各种兼容性或者Word的bug这类问题（文中您提到的Word的bug其实我一个都没有遇到过，所以甚至感到奇怪“为什么会有这么多问题？”），把时间拿去提升那些自己还很薄弱的地方不是更有价值吗？
   - 所以看到您对Word如此细致的了解以及你说“现在看来了解从前版本的Word还是很有意义的”这样的话感到很震惊，这就是清华学生的能力和素质吗（有点自惭形秽）
6. 其实这个问题就是我看到模版里面的叙述太详尽了，肯定需要来回对比检查补充，想问下您在如此繁杂的场景之下，有没有什么高效的管理这类文档的方式，我们那个项目也是需要写一个很复杂的文档，以致于前前后后改来改去乱成一团（见笑了）


[Markdown论文方案样品-2021.05.25.docx](https://github.com/qbh16/ThuWordThesis/files/6539189/Markdown.-2021.05.25.docx)

**Comment by fatalerror-i** [comment]
1. 关于页面顶端文字段前距的问题：目前认为一定和自定义xml有关，使得在“选项-高级-以下对象的布局选项”中，“取消页面顶部的多余行距”的勾选/反选在你的文档中可以生效，但在Word默认文档中不生效。
2. 关于文档内容管理：内容管理至今全靠自己在做，所以不涉及团队合作，也就没有什么高效管理的方式了，见笑😂话说回来，写技术文档之前，制定完善的文档规范还是有帮助的，不然很容易出现开发者和规范制定者相互鄙视的情况（doge
3. 关于了解不同版本的特性：往近了说，Word 2019和Office 365各有特性，Office for Windows和Office for Mac又是两样东西；往远了说，现在计算机Office二级用的还是2010版本，不少单位文职用的还是2003。能力范围内多了解些终究不是坏事，毕竟起码可以和与自己用不同版本软件的用户合作得更愉快些。
4.  `.md`转`.docx`的工作真的很奇妙——这也是我曾经希望自己未来可以做到的事情！👏
