### ISSUE TITLE
摘要部分页码错误问题

### ISSUE THREAD

**Issue by wpss929** [qbh16/ThuWordThesis#2]
百度云链接中的模版（即使用指南.docx）的摘要部分似乎存在页码问题：中英文摘要之间有一无页码的空白页面，中文摘要页码为I，英文摘要页码为III。将空白页删除后，中英文摘要的页码依旧保持I与III，即使重新将后者的页码链接到前页也不能解决该问题

**Comment by fatalerror-i** [comment]
中文摘要页尾的分节符使用了“分节符（奇数页）”，即下一节页码从奇数页开始。这是考虑到打印时中文摘要、英文摘要应该位于右页上才使用的，由此导致英文摘要页码为III。解决方法把分节符删掉换成“分节符（下一页）”即可。

这应该是设计之初考虑到空白页打印，但是后续没跟进空白页不计入页码、前后页码连续的要求所遗留的问题，而且这么久居然没被指出来，失误失误……
